vuejs/router

src/injectionSymbols.ts
Instead of Vue throwing `injection "Symbol(r)" not found.` when the router is not provided, it now throws a more explicit error in DEV mode:
injection "Symbol([view router]: router)" not found.
I think it gives a better hint to developers when encountering this issue.
=> feat: explicit injection symbols in dev mode

e2e/specs/transitions.js, e2e/transitions/index.html
When debugging via the HTML, the transition spec had the right html right before it was failing... so this is simply a matter of timing. By increasing the time the transition takes, we have a better chance of not failing.
I think that because each assertion takes at least 10-15ms. When the transition was set to 500ms, we were cutting it "too close". Sometimes the transition would finish before the assertions did.
Here's the command I used before/after the failures to console.log the body. I couldn't figure out the whole reporter ecosystem so I'm not sure how to bake this into Nightwatch's "afterEach" hooks to make CI debugging better.
```js
// ... assert, waitForElementPresent, etc
.source(result => console.log(result.value))
```
=> test(e2e): fix transition e2e specs by increasing css timing

README.md
`routes` should be an array instead of an object
=> Update redirect example syntax

__tests__/RouterView.spec.ts, e2e/keep-alive/index.html, e2e/keep-alive/index.ts, e2e/scroll-behavior/index.ts, e2e/specs/keep-alive.js, e2e/transitions/index.ts, package.json, playground/App.vue, src/RouterView.ts, yarn.lock
- Refactored `<router-view>` implementation
- Upgrading to `vue@3.0.0-beta.18`
- fixes navigation guard `this` when route component is inside `<keep-alive>`
- passing component vnode via `<router-view>` slot gets rid of the need to pass `props`, so the user no longer needs to bind it. This simplifies `<router-view>` slot usage with `<transition>/<keep-alive>` to:
```html
<router-view v-slot="{ Component }">
<transition name="fade" mode="out-in">
<keep-alive>
<component :is="Component"></component>
</keep-alive>
</transition>
</router-view>
```
[RFC](https://github.com/vuejs/rfcs/pull/160) needs to be updated accordingly.
- also added a warning when detecting old usage (`<router-view>` directly inside `<transition>/<keep-alive>`)
=> refactor: refactor router-view + fix keep-alive route guard this context

src/RouterView.ts
This adds a missing double quote in the deprecation warning using <router-view> inside <transition> & <keep-alive>.
=> fix: typo in <router-view> deprecation warning

README.md
I noticed it so I fixed it. Apologies for the tiny PR.
=> docs: Fix minor grammatical error in readme

__tests__/RouterLink.spec.ts
add not active with different params type and delete repeat test(`displays a link with a string prop` this part);
=> test(__tests__/RouterLink.spec): add not active with different params type and delete repeat test

__tests__/router.spec.ts
Add a warning test when `next` is called twice
=> test(__tests__/router.spec): add a warning test

__tests__/guards/guardToPromiseFn.spec.ts, src/navigationGuards.ts
Implements https://github.com/vuejs/rfcs/pull/187
=> feat(guards): allow guards to return a value instead of calling next

src/scrollBehavior.ts
closes #382 
chore: add (err) after catch, search with 'catch {' and confirm again with search '} catch'
=> chore: add (err) after catch, search with 'catch {' and confirm again with search '} catch'

__tests__/RouterView.spec.ts
Two test case are same:
```
it('passes params as props with props: true', async () => {
const { wrapper, route } = await factory(routes.withParams)
expect(wrapper.html()).toBe(`<div>User: 1</div>`)
await route.set({
...routes.withParams,
params: { id: '4' },
})
expect(wrapper.html()).toBe(`<div>User: 4</div>`)
})
it('passes params as props with props: true', async () => {
const { wrapper, route } = await factory(routes.withParams)
expect(wrapper.html()).toBe(`<div>User: 1</div>`)
await route.set({
...routes.withParams,
params: { id: '4' },
})
expect(wrapper.html()).toBe(`<div>User: 4</div>`)
})
```
=> test: delete duplicate test case

__tests__/guards/onBeforeRouteLeave.spec.ts, __tests__/guards/onBeforeRouteUpdate.spec.ts, e2e/guards-instances/index.html, e2e/guards-instances/index.ts, e2e/multi-app/index.ts, e2e/specs/guards-instances.js, playground/views/ComponentWithData.vue, src/RouterView.ts, src/navigationGuards.ts, src/router.ts
Close #444
Still worth adding edge cases
- Keep alive
- Dynamic names
=> fix(router-view): reuse saved instances in different records

src/index.ts, src/types/index.ts, test-dts/meta.test-d.ts
Ref https://github.com/vuejs/vue-router/issues/3183
Allow extending `meta` in TS:
```ts
declare module 'vue-router' {
interface RouteMeta {
requiresAuth?: boolean
nested: { foo: string }
}
}
export const router = createRouter({
routes: [
// error because `nested` is required
{ path: '/', component: Home, meta: {}
// No Error because `meta` can be omitted
{ path: '/', component: Home }
]
})
```
I don't know if there is a way of creating an error on the last one without going into generics since it involves making the `meta` field conditionally required
=> Allow defining properties in `meta`

src/globalExtensions.ts
closes #472
---
`declare module 'vue'` seems only to work if there is no other additional plugin
=> fix(types): extend @vue/runtime-core module

docs/guide/advanced/scroll-behavior.md
fixing the syntax in scroll behavior function, the `el: '#main'` should be in a comment and the element **el** should be in the returned object.
=> docs: improve scroll-behavior.md (#522) [skip ci]

src/RouterLink.ts, src/RouterView.ts, src/errors.ts, src/injectionSymbols.ts
There are some global variables that are not tree-shaked even we didn't use them.
Example here: https://github.com/antfu/vue-router-next-tree-shaking-test (bundle file under `/output`)
---
This PR adds `/*#__PURE__*/` for some global variables to improve the three-shaking.
However, TypeScript's enums still not be shook. Maybe we should switch to `const enums`. But as it alters the behavior, it's not included in this PR. (otherwise, we might need https://github.com/microsoft/TypeScript/issues/27604)
```bash
export-size . --bundler=rollup
```
```
export-size  v0.3.2
rollup       v2.31.0
terser       v5.3.5
vue-router v4.0.0-beta.13
┌───────────────────────┬──────────┐
│ export                │ min+gzip │
│                       │          │
│ createRouter          │ 10.34 KB │
│ …
```
=> refactor: add __PURE__ to improve tree-shaking

docs/api/index.md
I came across some broken links on the API Reference section of the documentation
=> docs: fix broken links on api reference

docs/api/index.md
Missing quote for `RouteLocationRaw` definition
=> docs: typo

src/devtools.ts, src/utils/index.ts
Fix #670 
1. use assign from utils.
2. add omit method to omit keys in object, like rest operator do.
=> fix(devtools): use assign instead of spread operator

__tests__/matcher/pathParser.spec.ts, src/matcher/pathTokenizer.ts
Clear customRe after consuming buffer to avoid re-use for subsequent parameters.
close #679
=> fix(matcher): clear customRe after consuming buffer

docs/guide/advanced/scroll-behavior.md
Added a missing comma in the code example.
=> docs: fix typo

docs/guide/essentials/dynamic-matching.md
The [code example in `pathMatch`](https://next.router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route) results in the target URL starting with 2 slashes and gives the following error in the console.
```
this.$router.push({
name: 'NotFound',
params: { pathMatch: this.$route.path.split('/') },
})
```
I suggest to remove the first slash from the `path` using `substring(1)` before breaking it to an array. 
```
this.$router.push({
name: 'NotFound',
params: { pathMatch: this.$route.path.substring(1).split('/') },
})
```
The issue can be reproduced here: https://jsfiddle.net/j4pqmvh8/
I've also included a short notice in the docs.
=> docs: improve 404 example

src/navigationGuards.ts
By using `console.error` even in the development environment, we will provide useful information such as the reference to the actual ES module that failed and the code line where it happened.
This is especially important if the errors happen in an imported package, no matter how deep it is.
See the comparison here:
- With the current implementation, which uses `warn` in dev and `console.error` in prod:
You can see that the stack trace is of no help at all.
- With `console.error` after the usual `warn`:
Now, the browser points me to the module that failed.
By the way, let me please celebrate the [almost All Lucky 7s](https://finalfantasy.fandom.com/wiki/All_Lucky_7s) PR 😆
=> refactor: use console.error during lazy loading

e2e/multi-app/index.ts, package.json, src/router.ts, yarn.lock
4.0.4
vue@3.0.6
[https://v3.vuejs.org/api/application-api.html#unmount](https://v3.vuejs.org/api/application-api.html#unmount)
* git clone https://github.com/vuejs/vue-router-next.git
* cd vue-router-next
* yarn add vue@next
* yarn test
All tests should pass
```
src/router.ts:1134:31 - error TS2554: Expected 1 arguments, but got 2.
1134         unmountApp.call(this, arguments)
```
---
https://github.com/vuejs/vue-next/commit/18b0c9a011b7569deae433fbbdf123764db2eae8
Close #793
=> refactor: remove unused parameter in unmount

__tests__/router.spec.ts, src/router.ts
=> feat(warn): throws if history is missing

docs/guide/advanced/meta.md
Without this change the example would have no exported members other than RouteMeta, a simple line of code such as:
```ts
import { createRouter } from 'vue-router'
```
Would throw the folloing error:
```
Module '"vue-router"' has no exported member 'createRouter'.
```
=> docs: fix RouteMeta typing example

docs/guide/advanced/meta.md, docs/zh/guide/advanced/meta.md, src/types/index.ts
added to the chinese docs and also recommending a file name `typings.d.ts` to make a bit clear on where it should be placed
=> docs: RouterMeta typing example

__tests__/parseQuery.spec.ts, src/query.ts
I drew attention to that when parsing the search query, it is possible to some extent manipulate the prototype of the returned object. I added a few checks so that at least partially prevent it.
=> fix: do not allow invalid hazardous keys in query

__tests__/stringifyQuery.spec.ts, src/query.ts
=> fix(query): `&` sign doesn't remove properly

docs/api/index.md
If i understood correctly addRoutes method is not in use any more,
so we could change router.addRoutes to router.addRoute
=> docs: change router.addRoutes to router.addRoute

__tests__/history/html5.spec.ts, src/history/html5.ts
=> fix(hash): allow characters after `#` in base e.g. `#!`

docs/guide/essentials/history-mode.md, docs/zh/guide/essentials/history-mode.md
1. Fix some typos.
2. Update `history-mode.md`, add an example that will work for Caddy v2.
=> docs: update history mode example

.gitignore
Ignore `webstorm` `.idea/` directory.
Ignore `vscode` `debug.log` file.
=> chore: ignore .idea/ and debug.log

docs/api/index.md
Fixes #953 
Add a bit more detail to the `scrollBehavior` API docs, and most importantly link to the very comprehensive guide.
=> docs: add scrollBehavior API detail and link to guide

docs/guide/essentials/passing-props.md
Highlighted the fact that in order for `props: true` to work, you need to explicitly define those props and name them correctly for the values to pass.
=> docs: note about new props when using props: true

docs/.vitepress/components/VueSchoolLink.vue, docs/.vitepress/theme/index.js, docs/guide/advanced/lazy-loading.md, docs/guide/advanced/transitions.md, docs/guide/essentials/dynamic-matching.md, docs/guide/essentials/history-mode.md, docs/guide/essentials/named-routes.md, docs/guide/essentials/nested-routes.md, docs/guide/essentials/passing-props.md
This PR adds Vue School links to the documentation to supplement the documentation with free training videos.
Here are screenshots of all the placements:
https://gist.github.com/danielkellyio/08ce944cff5e9fec67e04962174071ae
Lessons:
[Lazy Loading Routes](https://vueschool.io/lessons/lazy-loading-routes-vue-cli-only)
[Transitions](https://vueschool.io/lessons/route-transitions)
[Dynamic Routes](https://vueschool.io/lessons/dynamic-routes)
[Reacting to Param Changes](https://vueschool.io/lessons/reacting-to-param-changes)
[Catch All/404 Rotue](https://vueschool.io/lessons/404-not-found-page)
[History Mode](https://vueschool.io/lessons/history-mode)
[Named Routes](https://vueschool.io/lessons/named-routes)
[Nested Routes](https://vueschool.io/lessons/nested-routes)
[Route …
=> docs: add Vue school links

playground/main.ts
There is a error when run command `yarn dev`:
```
./playground/main.ts 13:4-23
[tsl] ERROR in D:\github\vuejs\vue-router-next\playground\main.ts(13,5)
TS2578: Unused '@ts-expect-error' directive.
```
I think we should remove the comment `// @ts-expect-error` in `playground/main.ts`.
=> chore(playground): unused '@ts-expect-error' directive

docs/guide/advanced/composition-api.md, docs/guide/advanced/extending-router-link.md, docs/guide/advanced/meta.md, docs/guide/advanced/scroll-behavior.md
This PR adds additional Vue School links to the documentation to supplement the documentation with free training videos.
Here are screenshots of all the placements:
https://gist.github.com/danielkellyio/b9bb9a3ed5754c01dbf5952e41e4f4a3
Lessons:
[Scroll Behavior](https://vueschool.io/lessons/scroll-behavior)
[Route Meta Fields](https://vueschool.io/lessons/route-meta-fields)
[Extending Router Link](https://vueschool.io/lessons/extending-router-link-for-external-urls)
[Vue Router and the Composition API](https://vueschool.io/lessons/router-and-the-composition-api)
Note: These are the 4 links mentioned in the [previous PR](https://github.com/vuejs/vue-router-next/pull/980) that were not ready at the time.
Thanks!
=> docs: add 4 Vue School links to docs

src/RouterLink.ts
This allows us to make vue-router optional while still being able to use the composable instead of router-link itself:
```ts
import { resolveDynamicComponent } from 'vue'
import type {
RouterLink as _RouterLink,
useLink as _useLink,
UseLinkOptions,
} from 'vue-router'
function useLink (props: Partial<UseLinkOptions>): ReturnType<typeof _useLink> | undefined {
const RouterLink = resolveDynamicComponent('RouterLink') as typeof _RouterLink | string
if (typeof RouterLink === 'string') return
const link = RouterLink.useLink(props as UseLinkOptions)
return props.to
? link
: undefined
}
```
=> feat(link): expose useLink on RouterLink as internal

docs/.vitepress/components/BannerTop.vue
This PR changes the banner on top of next.router.vuejs.org to inform visitors that it's less than 48 hours before the summer sale expires.
Please merge this Monday, 2021-06-21.
[Click here to see the visuals of the banner](https://imgur.com/a/0payFSI)
Related to [PR 991](https://github.com/vuejs/vue-router-next/pull/991)
=> docs: Update Vue School banner

docs/guide/migration/index.md, docs/zh/guide/migration/index.md
The `fallback` option has been removed now but not documented in `migration` docs.
I didn't add the `reason` of it, cause I'm not sure about the reason of the removal.
IMO, the reason of the removal of `fallback` is that the modern browsers all support `history.pushState` - except for IE, which is not supported by Vue 3.0. So we do not need a `fallback` option here. Am I right about this?
I can add the `reason` afterwards if needed.
=> docs: removal of fallback option

docs/.vitepress/components/BannerTop.vue
This PR changes the banner on top of next.router.vuejs.org to inform visitors that it's only a few hours before the Summer Sale expires.
Please merge on **2021-06-24** around **5:00 pm CEST**.
[Click here to see the visuals of the banner.](https://imgur.com/a/R7QaKWA)
Related to [PR 991](https://github.com/vuejs/vue-router-next/pull/991)
=> Docs: Update Vue School Summer Sale banner

src/types/index.ts, test-dts/navigationGuards.test-d.ts
Add support for `undefined` as the first argument in `next` function in navigation guards. I've decided to do it through making `location` argument optional since it seems to me as using `undefined` is omitting redefining the next route location.
Related to: https://github.com/vuejs/vue-router-next/issues/1058
=> fix(types): Support `undefined` in NavigationGuardNext 

docs/zh/guide/advanced/navigation-guards.md
英文原文为：
> `router.beforeResolve` is the ideal spot to fetch data or do any other operation that you want to avoid doing if the user cannot enter a page.
=> docs(zh): Update zh translation: navigation-guards.md

docs/guide/advanced/meta.md
A missing comma in the code example that would lead to an error has been added.
=> docs: added missing comma

docs/guide/essentials/redirect-and-alias.md
1.The example`/home` is above the text instead of below.
2.Add description on [Relative redirecting](https://next.router.vuejs.org/guide/essentials/redirect-and-alias.html#redirect) example
=> docs: relative redirect improvement

__tests__/history/memory.spec.ts, src/history/memory.ts
Ensure base is normalized in memory history.
When using memory history with slash-trailing base (e.g. `/foo/`), `router.resolve().href` will combine base and normalized location (e.g. `/bar/`) directly, this will cause double-slashes in href url.
To fix this issue, ensure base is normalized just like we have done in html5/hash history.
=> fix(history): ensure base is normalized in memory history

docs/.vitepress/components/BannerTop.vue
This PR changes the banner on top of next.router.vuejs.org to inform visitors that it's less than 48 hours before the BTS sale expires.
Please merge this Monday, 2021-10-04.
=> Docs: Update Vue School BTS 21 banner

src/matcher/types.ts, src/router.ts
=> chore: fix incorrect jsdoc links [skip ci]

src/router.ts
Currently referencing the non-existant `parse` property instead of `parseQuery`
=> Fix qs example [ci skip]

docs/guide/essentials/redirect-and-alias.md
I found that I had to re-read this section a couple of times, to figure out which was `a` and which was `b`. It would be easier to understand if the text reflected the example.
=> docs: better example

docs/.vitepress/components/VueSchool/BannerCoins.vue
This PR updates the animation of the background coins of the Vue School Black Friday banner.
Related to [1198](https://github.com/vuejs/vue-router-next/pull/1198)
=> Docs: Update Vue School Black Friday banner animation

docs/.vitepress/theme/Layout.vue
This PR removes the Vue School Black Friday banner introduced in https://github.com/vuejs/vue-router-next/pull/1198
Please merge this **Friday Dec 10th**.
The landing page will keep working after the promo ends, so the link (https://vueschool.io/sales/blackfriday?friend=vuerouter) will still be valid.
=> Docs: Remove Vue School's Black Friday banner

docs/guide/essentials/passing-props.md
The link was leading to the old vue-router 3.x example.
Removed misleading line
=> docs: remove old link

docs/guide/essentials/history-mode.md
On the HTML mode section: i think it's good to specify  HTML mode and not history mode this will make the sentence sound more clear **When using HTML mode, the URL will look "normal," e.g. `https://example.com/user/id`. Beautiful!**
=> Update explanation on HTML mode

docs/api/index.md, docs/guide/essentials/route-matching-syntax.md
Hi @posva 
I have two open points that I would need your feedback on:
- Is the example with setting` strict true` on the top level and setting `sensitive` on a specific route enough or should I add more examples? Or do you prefer a different example?
- In the corresponding closed issue it's mentioned that  documentation should also be on the API docs for the RouteRecordRaw - is this needed from your perspective? 
I will complete this change once I have your response. 
Thanks and regards!
=> docs: document strict and sensitive option

src/devtools.ts
The logo link is no longer valid due to the update of the official website。
=> docs: Invalid logo link (#1309) [skip ci]

docs/guide/advanced/navigation-guards.md
Added an example where the guard returns a route location object, to help clarify what can be returned from a navigation guard. This supplements the examples where the guard returns false or a simple string path.
=> docs: add redirect guard example

docs/guide/essentials/route-matching-syntax.md
`RegExp` is the name of the object in JavaScript. The word "regex" is more generic and a shorthand for "regular expression".
=> Rephrase Regexp to regular expression

__tests__/matcher/addingRemoving.spec.ts, src/matcher/index.ts
fix(matcher): correctly renders child when it is added dynamically and both it and its parent have an empty path
close #1124
=> fix(matcher): add child before parent when using `addRoute` (fix #1124)

docs/index.md
add a link to the Vue Router video course on the homepage
Thanks!
=> docs: add link to vue router video course on home page

docs/guide/advanced/composition-api.md
Changes "It gives access the..." to "It gives access to the..."
=> docs(composition-api): add missing "to" in `useLink` section

docs/.vitepress/components/VueSchool/BannerTop.vue
This PR updates the free weekend banner to include the logo in the mobile viewport.
[Screenshot](https://imgur.com/a/6DnCDWr)
Related to https://github.com/vuejs/router/pull/1359
=> Show Vue School logo in free weekend banner mobile

package.json, src/globalExtensions.ts
This allows Volar to provide intellisense and syntax highlighting.
Without the GlobalComponents interface:
With the GlobalComponents interface:
=> feat: expose RouterView and RouterLink as GlobalComponents

docs/guide/advanced/meta.md
The given documentation was not working.
To augment (and not replace) the existing RouteMeta interface of vue-router, one has to define a module.
=> docs: improve meta extending

docs/.vitepress/components/VueSchool/BannerTop.vue, docs/.vitepress/theme/Layout.vue
This PR updates the text of the Vue School top banner to announce the promo is extended for 48 hs.
Please merge this on `2022-05-01T00:00:00+02:00` (so, on the first minute of Sunday, or soon later).
The banner will stop appearing automatically on `2022-05-04T00:00:00+02:00`, the date is hard-coded.
[Click here to see screenshots of the banner](https://imgur.com/a/2yH6QEC)
=> Update Vue School banner copy

docs/guide/essentials/navigation.md, docs/guide/essentials/route-matching-syntax.md
=> docs: fix typos

__tests__/errors.spec.ts, __tests__/matcher/resolve.spec.ts, __tests__/mount.ts, __tests__/utils.ts, playground/router.ts, playground/tsconfig.json, src/RouterLink.ts, src/globalExtensions.ts, src/index.ts, src/injectionSymbols.ts, src/location.ts, src/matcher/index.ts, src/matcher/pathParserRanker.ts, src/router.ts, src/typedRouter.ts, src/types/index.ts, src/types/named.ts, src/types/paths.ts, src/useApi.ts, src/utils/index.ts, test-dts/index.d.ts, test-dts/namedRoutes.test-d.ts
WIP to support typescript named routes
~~## Limitations
`ExtractNamedRoutes` needs all the routes to have `children:[]` declare if one has `children`.
All the routes must have `name`~~
Close #1160
=> feat: support for typescript named routes

docs/guide/essentials/history-mode.md
I spent a lot of time searching for what turned out to be the "abstract history mode". I was only able to find a mention of this mode in the ["Migrating from Vue 2" section](https://router.vuejs.org/guide/migration/index.html#new-history-option-to-replace-mode).
The abstract mode can be a very useful tool for some micro-services or wizard-like apps. In some applications it may be considered a bad practice, but I think there are very valid applications where SEO does not matter and the app should not return the current view after reload.
=> docs: mention abstract history mode in the guide

docs/api/index.md
In the source, the type of RouteLocationNormalized.query is a Record<string, LocationQueryValue | LocationQueryValue[]>.  LocationQueryValue isn't exactly a string, but is a (string | null). I think it makes sense to update the docs, especially since LocationQueryValue isn't assignable to string.
=> docs: Change type to LocationQueryValue to accurately reflect source.

docs/installation.md, docs/zh/installation.md, index.cjs, index.js, package.json, rollup.config.js, yarn.lock
This PR proposes using `.cjs` and `.mjs` instead of the current `.js` extensions. That will allow usage of this library in a native Node module context.
| **old**                   | **new**                    |
| ------------------------- | -------------------------- |
| vue-router.cjs.js         | vue-router.cjs             |
| vue-router.cjs.prod.js    | vue-router.prod.cjs        |
| vue-router.esm-bundler.js | vue-router.mjs             |
* As is, this is a **breaking change** as it changes the packaging expectations. I've added stubs that re-export these `.mjs`/`.cjs` files for backwards compatibility.
* Because this package imports `vue`, `vue` will also need to provide appropriately named native Node module filenames. (This should not negatively affect existing users who will not …
=> build: use cjs/mjs extensions for cjs/esm builds

src/RouterLink.ts
In particular, without this `<router-link @click="foo">` does not trigger `foo` under the compat build.
=> fix(compat): force router-link mode to Vue 3

packages/router/package.json
Fixes https://github.com/vuejs/router/issues/1456; see also https://github.com/microsoft/TypeScript/issues/47792
=> fix(types): adds ESM export of types

packages/router/package.json
resolves https://github.com/gtm-support/vue-gtm/issues/226
=> fix: allow requiring in cjs context

packages/router/src/navigationGuards.ts
The first feeling here is that the logic is not easy to understand without the brackets
=> style: code prettier

packages/docs/api/index.md, packages/router/e2e/modal/index.html
Docs-API: Links with typos. `(#addroute-2)` → `(#addroute)`
Router-Ex: Works fine, but typo in alpha value in css color. `rgb` → `rgba`
=> Docs and Router-Example typo fix.

packages/docs/.vitepress/components/VueSchool/BannerCountdown.vue, packages/docs/.vitepress/components/VueSchool/BannerTop.vue, packages/docs/.vitepress/theme/Layout.vue, packages/docs/package.json, pnpm-lock.yaml
This PR updates the banner introduced by https://github.com/vuejs/router/pull/1446
The banner at the top of https://router.vuejs.org/ informs users about Vue School’s Summer Sale promotion.
The banner is closable and opens Vue School's Summer Sale promo page in a new tab. The banner will not reappear if a user has closed it (stored in localStorage).
Please note that this banner includes a countdown. The component uses `@chenfengyuan/vue-countdown`.
[Click here to see screenshots of the banner](https://imgur.com/a/0NGoeyM)
=> Update Vue School summer sale banner

packages/docs/guide/essentials/nested-routes.md
To avoid something like #1493
now it is clear why it works like this, clarified it in the docs as a reminder
=> docs(nested-routes): add note for named routes

packages/docs/guide/advanced/lazy-loading.md
=> docs: fix link to dynamic import docs (fix #1498)

packages/docs/.vitepress/components/VueSchool/BannerTop.vue
This PR fixes the incorrect URL of the Vue School banner.
=> docs(docs): Fix link to Vue School banner to show Vue.js Forge offer

packages/docs/guide/advanced/data-fetching.md
In my testing with v4.1.5 the callback provided to next within beforeRouteEnter is evaluated *after* mount. I'm not 100% sure it's actually what happens reliably, but it's what my test showed. Seems like quite strange behavior if it is indeed true, so thought should make note in doc.
=> docs: beforeRouteEnter next callback

README.md
GitHub treats non-https-prefixed links as relative paths, resulting in 
https://github.com/vuejs/router/blob/main/www.vuejs.de
=> chore: bronze sponsor link [skip ci]

packages/docs/.vitepress/config.ts
Currently, the edit link text in zh docs is in english.
This PR fixes it.
=> docs: replace zh docs edit link text in chinese

README.md
- Bullet points used, since without them the quote gets merged in one line.
- The same style is also used in the [README of vue-router 3](https://github.com/vuejs/vue-router/blob/dev/README.md?plain=1#L3-L5).
- Since vue-router v1 is old already I didn't see the need to add a link for that.
=> chore: add link to Vue2 router aka Vue Router 3 (#1595) [skip ci]

packages/docs/guide/advanced/transitions.md, packages/docs/zh/guide/advanced/transitions.md
In en docs they both being **meta.transitionName**
In zh docs, **route.meta.transition** mismatch with **to.meta.transitionName**
=> docs: fix zh docs dynamic transition name mismatch error

packages/docs/guide/advanced/composition-api.md
The `pushWithQuery` function accepts a `query` argument that was not used. I updated the docs to how I assume the function was mean to be set up.
=> Update `pushWithQuery` example function

packages/docs/guide/advanced/transitions.md
Edit link to v-slot API documentation 
from:
https://router.vuejs.org/api/#router-view-s-v-slot
to:
https://v3.router.vuejs.org/api/#v-slot-api-3-1-0
=> docs: remove dead link

packages/docs/zh/api/index.md
References should not be translated.
=> docs(zh): typo

packages/docs/guide/advanced/transitions.md
Should be `route.meta.transition` instead of `route.meta.transitionName`
=> docs: Fixed typo in transition example

packages/docs/guide/advanced/composition-api.md
I found this a little enhancement for the `Composition API` section.
It is to let clear what functions you need to use to access the
`Router` and `Route` objects inside a `setup` method.
=> docs: mention both `useRoute` and `useRouter` functions

packages/docs/guide/essentials/history-mode.md
The link to `createWebHistory` was broken
=> docs: link to `base` property of the router

packages/docs/guide/essentials/nested-routes.md, packages/docs/zh/guide/essentials/nested-routes.md
Add missing `,` string in example code.
The Chinese document was also revised at the same time.
=> docs: simple typo code correction

scripts/release.mjs
globby is have a bug in windows,can see this issues :https://github.com/sindresorhus/globby/issues/179. It's not a serious bug，But it makes learning to code tricky.
=> chore: modify the way to get folders

.github/workflows/test.yml
fix github action :The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: fix GitHub Actions Deprecating save-state and set-output commands

packages/router/__tests__/guards/extractComponentsGuards.spec.ts, packages/router/__tests__/utils.ts, packages/router/e2e/guards-instances/index.ts, packages/router/e2e/modal/index.ts, packages/router/e2e/suspense/index.ts, packages/router/src/history/html5.ts, packages/router/src/location.ts
Summary
This PR removes the unnecessary await keyword from extractComponentsGuards and makes some minor adjustments.
=> chore: remove unnecessary await keyword 

packages/docs/guide/advanced/navigation-failures.md
Remove reference to `NavigationFailureType.redirected` which is no longer available on vue-router v4.
=> docs: Update navigation-failures.md

packages/docs/zh/guide/advanced/composition-api.md, packages/docs/zh/guide/advanced/dynamic-routing.md, packages/docs/zh/guide/essentials/history-mode.md, packages/docs/zh/guide/migration/index.md
- Range: e008551...1a3a28f
@posva would you mind granting permission to @Justineo to review/maintain the zh docs?
Thanks.
=> docs(zh): sync update to 1a3a28f

.github/contributing.md
Ref: https://github.com/vuejs/router/discussions/1770#discussioncomment-5526951
Thanks.
=> chore: add translation guide into contributing.md

packages/docs/.vitepress/config/zh.ts
Currently, zh docs have no Typed Routes entry in the sidebar.
=> docs(zh): update typed routes sidebar

packages/docs/zh/guide/advanced/navigation-failures.md
above document and english docs, there should be `aborted`
=> docs(zh): fix typo

.github/contributing.md
@posva for translations hosted in a different repo, I added more content in the `contributing.md`. Do you think that makes sense? Thanks.
=> chore: add the guide for self-host translations [skip ci]

packages/router/__tests__/router.spec.ts, packages/router/src/router.ts
This line appears in `router.ts`:
```js
const targetParams = assign({}, rawLocation.params)
```
The lines that follow update the contents of `targetParams` to remove nullish values, but that object is never actually used anywhere.
That code was introduced in change ebca15a0140453c6671fdae7a9864badc650531e. From what I can tell, `targetParams` was supposed to be used to build `matcherLocation` on the lines that follow, but instead it is using the original `rawLocation.params`.
The accompanying test also contains a problem. It is using `toMatchObject()` to verify that the `params` object is empty. Unfortunately, `toMatchObject()` only checks properties that are present in the expectation, it won't fail for any extra properties that are present. So even though it appears to be verifying that …
=> fix: remove nullish params when resolving

packages/docs/zh/guide/advanced/navigation-guards.md
发现翻译错误
”正确调用“  @line: 89
原文：but resolve guards are called right before the navigation is confirmed
=> found a translation mistake @navigation-guards.md

packages/docs/.vitepress/config/index.ts
I would appreciate it if you could approve this PR so that more Koreans can see it. (Though the translation for the API section is not yet completed.)
(I have activated both the VueSchool links and Carbon ads.)
Please let me know if there's anything lacking!
Thank you.
=> docs(ko): add ko-KR translation

packages/docs/.vitepress/theme/components/VueSchoolLink.vue
The play button icon on the Vue School links is broken:
This fixes:
=> fix: broken play icon on vue school links

packages/docs/.vitepress/config/en.ts
This PR adds the link to the Vue.js Certification in the Navbar.
=> Docs: Add Link to Vue.js Certification

packages/docs/guide/migration/index.md
Howdy folks,
Just raising this PR to add some extra guidance on the `currentRoute` object being changed to a reactive object in vue-router v4. We got a little tripped up on this during our migration to Vue 3/Vue-Router 4 as I couldn't find any docs that explicitly mentioned this change, and how it may impact code accessing router information from outside a Vue template.
I'm hoping the place I've put it in is ok, but if its not, let me know and I'm happy to change it :)
Cheers,
Adam
=> docs(migration): provide guidance on using the new reactive currentRoute

packages/router/src/types/utils.ts
Our friends at the end of the alphabet seem to have gotten left out, I assume unintentionally
=> Add z/Z to alphanumeric characters

packages/docs/.vitepress/config/index.ts
After translating the documentation of the Pinia library into Russian (the link has been added to the official documentation, [repository with translations](https://github.com/translation-ru/pinia)), I have started working on translating the documentation for Vue Router. All translations are being done within the scope of the organization https://github.com/translation-ru.
The current status of the documentation translation for Vue Router can be found [here](https://github.com/translation-ru/vue-router/issues/1).
Sync with the head repo is done through https://github.com/vuejs-translations/ryu-cho.
After adding a link to the Russian version of the Vue Router documentation, I plan to gather more people from the community to work on translations for Vue Router documentation and other …
=> docs: Add link to Russian docs

packages/docs/guide/advanced/navigation-failures.md
added comma while passing params to sendToAnalytics function in doc.
=> Update navigation-failures.md. Added comma while passing params to sendToAnalytics function in doc.

packages/docs/guide/advanced/composition-api.md, packages/docs/guide/advanced/lazy-loading.md, packages/docs/guide/advanced/navigation-guards.md, packages/docs/guide/advanced/transitions.md, packages/docs/guide/essentials/history-mode.md, packages/docs/zh/guide/advanced/composition-api.md, packages/docs/zh/guide/advanced/lazy-loading.md, packages/docs/zh/guide/advanced/navigation-guards.md, packages/docs/zh/guide/advanced/transitions.md, packages/docs/zh/guide/essentials/history-mode.md, packages/docs/zh/introduction.md
I've updated links to the docs for Vue core.
In most cases these were links to `v3.vuejs.org`. These had redirects configured and in most cases I just updated the link to reflect the location of the redirect.
For the Chinese translation I linked to `cn.vuejs.org` instead.
`history-mode.md` contained a link to `https://v3.vuejs.org/guide/ssr/introduction.html#what-is-server-side-rendering-ssr`. That link was broken and just led to the Vue homepage. I've updated it to point at the SSR guide, which is the closest match I could find. However, unlike the old SSR guide, the current SSR guide doesn't mention routing at all, so I'm not sure whether it's really equivalent.
=> docs: update links to the core Vue docs

packages/docs/.vitepress/config/en.ts, packages/docs/guide/advanced/router-view-slot.md, packages/docs/guide/advanced/transitions.md, packages/docs/guide/essentials/passing-props.md
The slot for `RouterView` is mentioned in a few places within the docs, but it isn't directly explained anywhere. This PR adds a new page to the advanced guides covering that topic.
Perhaps this isn't the best way to introduce the topic, but maybe it'll be useful as a starting point to discuss it further.
I've put this guide just before the guide to transitions, as that guide heavily relies on using the slot. The slot is also used in the earlier guide to passing props, but I didn't think it made sense to have this new page in the **Essentials** section. Instead, I've just linked to the new page from that earlier page.
There are a few things I would like any reviewers to consider:
- Any suggestions for improvements to the file name and page title? `router-view-slot.md` and `RouterView …
=> docs: add a guide to the RouterView slot

packages/docs/guide/advanced/transitions.md, packages/docs/guide/essentials/named-routes.md, packages/docs/guide/essentials/named-views.md, packages/docs/guide/migration/index.md, packages/docs/zh/guide/advanced/transitions.md, packages/docs/zh/guide/essentials/named-routes.md, packages/docs/zh/guide/essentials/named-views.md, packages/docs/zh/guide/migration/index.md
Using `vue-html` for the language of code blocks allows them to highlight Vue template syntax correctly. In particular, directive values are treated as JS expressions, rather than just HTML attributes:
In a few cases I've also changed `vue` to `vue-html`. Using `vue` as the language requires the surrounding `<template>` tag, otherwise it won't be highlighted correctly. `vue-html` treats the whole block as template syntax, even without a `<template>` tag.
It isn't always clear whether an example should be treated as `vue-html` or `html`. Some examples are using in-DOM templates and only part of the HTML should be treated as a template. In those few examples I left it as `html`.
I've made the same changes to the Chinese translation.
=> docs: use vue-html for template examples

packages/router/__tests__/urlEncoding.spec.ts, packages/router/src/location.ts
=> fix: decode hash when parsing urls

packages/docs/guide/advanced/transitions.md
The word `fallback` was removed by this change: https://github.com/vuejs/router/commit/950681aac7428cd91b47fd0b7a6aecb2b51c016f. This seems to have been unintentional.
I've reintroduced the word `fallback`. I also didn't think that `any` was quite the right word here, so I've made a couple of other tweaks to the wording.
=> docs: update custom transition example

packages/docs/installation.md
There were a few preliminaries that I felt were missing from the **Installation** page. I'm not sure how many people actually read that page, but at least the extra information will be explicitly stated for anyone who does.
I imagine this page will undergo significant changes when the docs are rewritten next year, but I thought it was worth making these additions now.
1. I've explicitly noted that `VueRouter` is exposed as a global object when using the global build.
2. I've added installation instructions for `pnpm`, alongside `npm` and `yarn`. To keep things concise, this is wrapped in a VitePress code group, similar to how commands like these are presented in the Vite docs.
3. I've tried to encourage newcomers to use `create-vue` instead.
4. I've added a note about how to access Vue …
=> docs: expand installation.md

packages/router/src/location.ts
The final element in the `toSegments` will always be empty or a string that is not `.` or `..`.
As a result, the `toPosition` will not increment when it exits the `for loop` and it will always be shorter than `toSegments' length`.
=>  Maybe it's unnecessary to add this judgement

package.json, packages/playground/package.json, packages/router/__tests__/router.spec.ts, packages/router/__tests__/warnings.spec.ts, packages/router/package.json, packages/router/src/errors.ts, packages/router/src/matcher/index.ts, packages/router/src/router.ts, packages/router/src/types/index.ts, pnpm-lock.yaml
From https://github.com/vuejs/router/pull/1904
Still need to check if we can avoid the `path?: undefined` in newer versions of TS.
=> fix: allow undefined path in router resolve

packages/docs/zh/guide/advanced/navigation-failures.md
应当去掉“还没有”，把文本改为“在当前导航完成之前又有了一个新的导航”。
=> docs(zh): Update navigation-failures.md

packages/docs/.vitepress/theme/components/VueMasteryBanner.vue
fix: #2096 
It seems that " --vt-banner-height " is not used in class " aside-container ".
And " --vp-layout-top-height " has no value in here, so I set it.
=> docs: style error caused by banner

packages/docs/package.json, pnpm-lock.yaml
Support adding dir in meta like:
```md
---
dir: rtl
---
```
The demo screenshot
So we can control the direction per each page.
Thanks.
/cc @brc-dd
=> docs: support dir in meta for pages

packages/docs/.vitepress/theme/index.ts
I saw this commit (https://github.com/vuejs/router/commit/4e26035df5ee515e432167134835fb36f75fff71) and found that the corresponding import may be deleted.  So I casually submitted a PR.🤣
=> docs: delete useless import

packages/router/__tests__/guards/navigatioGuardsInjections.spec.ts, packages/router/src/navigationGuards.ts, packages/router/src/router.ts
Fix vuejs/router#2051
Close #2053
The PR is based on the https://github.com/vuejs/router/pull/2053
=> fix(guards): run beforeRouteEnter with app context

packages/docs/.vitepress/theme/index.ts, packages/docs/guide/essentials/nested-routes.md
close #1810
The change to `index.ts` is intentional. Extending a theme in VitePress is now done using `extends` rather than `...`. The main difference is that `extends` will ensure `enhanceApp` is called on `DefaultTheme`. This is needed for the `<Badge>` to work.
The example is based on a similar example given at <https://github.com/vuejs/router/pull/1397>.
=> docs: omitting parent components for nested routes

packages/router/__tests__/router.spec.ts, packages/router/src/router.ts
This adds a warning when calling `router.addRoute('foo', { ... })` if the parent route isn't found.
Without this warning, it can be difficult to tell why `addRoute` isn't working correctly. With an absolute path, beginning with `/`, the addition seems to succeed, but the new route won't be a child of the intended parent. With a relative path, it'll fail to add the new route, but with a confusing error about the `path` being invalid.
I've also added a test for the similar warning in `removeRoute`, though the warning itself already existed.
=> feat(dx): warn when `addRoute` cannot find the parent

packages/docs/zh/guide/index.md
missing space between comment symbols and text.
=> docs(zh): fix the comment format in packages/docs/zh/guide/index.md

packages/router/__tests__/router.spec.ts, packages/router/__tests__/useLink.spec.ts, packages/router/src/RouterLink.ts, packages/router/src/devtools.ts, packages/router/src/router.ts, packages/router/src/utils/index.ts
This PR attempts to improve the warnings and error handling for a common problem encountered during development.
There's an error message I've encountered several times on Vue Land:
> TypeError: Cannot use 'in' operator to search for 'path' in undefined
This comes from `router.resolve()`, e.g.:
- [Playground](https://play.vuejs.org/#eNp9UV1PgzAU/SsNL2zJgESnDyQmi2aJmviR6Zv1gcEddIOWtIVhCP/d24L70DleWs49Pfece1uniBj318oJHVaUQmrSklhCpOEJCiG/7pnSeEwGcCEqDZJ0ZCVFQdy6Ak9ayKWc8lhwpUkPkJujJ6OWckKyXi081WI0nhiKfa1C8mF+CLHPzFdGOguJG7iWZb5YoGEOXIek7XrQHp+Ud2NjpzfiS1Air2FU8QRWjEMydiZDWK+ISgwvOMa3nehQUNRB1V6UOvuYBqZOpnWpwiCoeLlJffQR7BmzqX/hXwUJhjpAfVCFt5Riq/C+RvUhBXVmSAoSqLUQufKikv3X4g9xdu1PsVPOlgGqBwzjNVbbSOMkOoypFe5kxdJfIc3oWA7ypdQMd3YUNspzsX20mJYV7IzGGcSbE/haNb3lVxw0yBoOwulIpqD78vztGRq874qFSKoc2WeKC7O6y …
=> feat(dx): warn when passing undefined/null locations

packages/docs/zh/guide/essentials/passing-props.md
[2024.03.06] UPDATE: 
Before: 
After:
=> docs(zh): translate the warning part of passing_props to Chinese

packages/docs/guide/advanced/composition-api.md, packages/docs/guide/advanced/data-fetching.md, packages/docs/guide/advanced/dynamic-routing.md, packages/docs/guide/advanced/extending-router-link.md, packages/docs/guide/advanced/meta.md, packages/docs/guide/advanced/navigation-guards.md, packages/docs/guide/essentials/dynamic-matching.md, packages/docs/guide/essentials/named-views.md, packages/docs/guide/essentials/nested-routes.md, packages/docs/guide/essentials/passing-props.md, packages/docs/guide/index.md, packages/docs/installation.md
- Switch examples to use SFC syntax.
- Include Composition API examples with `<script setup>`.
- Update the wording to take account of the Composition API, including changing any wording that makes it sound like a new, exotic choice.
There are lots of other changes that might be desirable, but I've tried to stick to that scope as much as possible. For the most part, the order and flow of the existing docs has been retained.
These changes need making in one big jump to keep the guide consistent. Migrating one page at a time would just make the guide highly confusing.
I am aware that big changes like these are a burden for translators. I've tried to take that into account where possible.
In many cases, the change just involved switching an existing example to use SFC syntax.
In examples …
=> docs: update examples to use SFCs

packages/docs/.vitepress/config/en.ts, packages/docs/guide/essentials/named-routes.md
There are several problems I was trying to address:
1. Named routes are used in earlier pages, particularly the **Nested Routes** and **Programmatic Navigation** pages, which use them quite heavily.
2. The list of advantages comes too soon. A reader will struggle to understand that list until they have seen the example.
3. Advantage 2 on the list mentions `encoding/decoding`. As far as I can tell, that should just be `encoding`, as named routes don't impact decoding.
4. Advantage 4 stops mid-sentence. `Bypassing path ranking (e.g. to display a )`.
5. The linked example is for Vue 2.
While I've reworded and reordered much of the page, the material covered should be the same.
I've tweaked the example to use `name: 'profile'`, rather than `name: 'user'`. This was to avoid the `name` …
=> docs: rewrite the Named Routes page

packages/docs/.vitepress/config/en.ts, packages/docs/guide/essentials/active-links.md, packages/docs/guide/essentials/router-link-classes.md
This adds a page explaining the RouterLink classes.
This currently isn't covered in the main guide. It is mentioned in the [migration guide for the `exact` prop](https://router.vuejs.org/guide/migration/#Removal-of-the-exact-prop-in-router-link-). There's also an explanation in the [related RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md).
I've put it near the end of the **Essentials** section. It mentions `alias` and `redirect`, so it needed to come after those are introduced. Putting it after the guide to passing props was an arbitrary choice, it could just as easily have gone before.
There's already an advanced guide to **Extending RouterLink**. That page seems to assume that people are already familiar with the existing RouterLink classes and the …
=> docs: add 'Active links'

packages/router/__tests__/router.spec.ts, packages/router/src/router.ts
=> fix: avoid normalizing the fullPath

packages/docs/.vitepress/theme/styles/sponsors.css
In this pull request, I am temporarily correcting the become sponsor button text color when hovering.
| Before      | Now      |
| ------------- | ------------- |
| ![become-sponsor-button-before-2024-05-25_22 21 39](https://github.com/vuejs/router/assets/31008635/faa22184-4b0f-43fc-9f17-827b934bd8ec) | ![become-sponsor-button-now-2024-05-25_22 23 06](https://github.com/vuejs/router/assets/31008635/a073d9d8-3bda-477d-81a5-94c269436400) |
=> docs: correct become sponsor button text color when hovering

packages/router/src/globalExtensions.ts
after
I noticed the comment : `// TODO: figure out why it cannot be 'vue' like said in docs`, actullay, it works in the latest version of vue(3.4.31)
=> fix: router typescript definations related to vue package

packages/docs/guide/essentials/route-matching-syntax.md
=> docs: mention an edge case with mutliple optional params in the docs

packages/docs/guide/essentials/route-matching-syntax.md
Add a single backtick causing code rendering issue
=> doc: add missing backtick

packages/router/package.json
In the `exports` of `package.json`, place the `.` entry higher than `./auto-routes` and `./auto`.
This can prevent `./auto-routes` and `./auto` from overriding `.` in certain import scenarios.
> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.
https://nodejs.org/api/packages.html#conditional-exports
- https://github.com/nuxt/nuxt/issues/28218
- https://github.com/nuxt/nuxt/pull/28333
=> chore(router): reorder exports in `package.json`

packages/router/rollup.config.mjs
Fixes a build error on newer versions of Node.js. Import attributes by specification should use `with` keyword instead of `assert` and it's already on stage 3, so proposal is accepted. https://github.com/tc39/proposal-import-attributes
This is also mentioned in TypeScript 5.3 https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/#import-attributes
```
Scope: 3 of 4 workspace projects
packages/router build$ rimraf dist && rollup -c rollup.config.mjs
│ [!] SyntaxError: Unexpected identifier 'assert'
```
=> chore: use `with` instead of `assert` in rollup.mjs

packages/docs/guide/migration/index.md
The  onDemand and onAbort  callback arguments for router.push and .replace were deprecated in v4. I added a section to the migration guide explaining that users should replace them with the thenable Promise the methods return.
=> Section about deprecated onDemand and onAbort callback arguments

packages/router/__tests__/guards/loadRouteLocation.spec.ts, packages/router/src/navigationGuards.ts, packages/router/src/utils/index.ts
- https://github.com/nuxt/nuxt/pull/28912
=> fix(ssr): handle symboless Modules in dynamic imports

packages/router/__tests__/RouterLink.spec.ts, packages/router/src/RouterLink.ts
=> fix: custom directive doesn't work when custom=true

packages/router/__tests__/matcher/pathParser.spec.ts, packages/router/src/matcher/pathParserRanker.ts
This Playground illustrates the problem:
- [Playground](https://play.vuejs.org/#eNp9U8Fu2zAM/RVBFzdAbK1It4PhBtmGAtuAbkW3W7WDYzOxW1sSJDnN4PrfR0lN7G5pfTH1+Eg+klJPPyqV7DqgKc1MoWtliQHbqSUXdauktqQnhYbcwjW0Uv/5UhuLv/kzeCs7C5oMZKNlSyJMFGsPRVxwUUhhLAkAuXwRctZzQUgVsqWnSpzN5o7io01K7tyBEB/mPpG3kJLIu88jT3Wfym2FMOsMaDbCxuq6sCmxuoMjCKJMySZvzAgVEpsWIJDaDwH0v99cDLOxJVfFYEd3oVA0f66IQsbaB+s8wuiMheniXPFgoVUNNownQjKbrxsga6lL0B5x2MFydrW8wYIZQ2MKXue2qMBMcDQnGcgu3kh9yamTS2oRZHM6SVIuM6Vh2ffeR4YhY+6MecqTrLDLRIORzQ7OXNAscasgT08kiqNTGY6i0HCdoo3WYQJ0Tq3BqW7qbXJvpMCL6HfMqdtF3YD+oWyNU+cUdxIycpo3jXz85rHJSjGmguLhBH5v9g7j9Aalg94Bp0efzfUWbHBf/fwOe7SPzlaWXYPsN5y3bhid0xhonzpRouwJz6v96p9TLba/zNXegjCHppxQxxw8n1N8RJ/faH2Uu0gWPg7vJk4xPNe4zdU/cwyOl0nGhxo0V9YqkzLWCfWwTXDybGSsLpJF8o6V+CwnaAKmjddaPuI4seCk2xWSWAk7K2Vj4lzVr5X4j7j6kFwk …
=> fix: combining 'end' and 'strict'

packages/router/__tests__/matcher/addingRemoving.spec.ts, packages/router/src/matcher/index.ts
#2266 demonstrated an edge case that can lead to inconsistent internal state in the matcher.
The problem arises when using nested routes. If the child (or deeper descendant) has the same `name` as its parent, the parent is removed at the same time that the child is added.
Removing a parent route should also remove its children, but in this case that removal happens just before the child is added to the matcher. The child still gets added to the matcher, and its `parent` property still points to the parent route, even though that has now been removed. The parent can no longer be resolved directly, but when resolving the child, the `matched` array will still contain the removed parent.
This problem can occur during the initial router creation:
```js
createRouter({
// ...
routes: [{
name: …
```
=> feat: throw if parent and child routes have the same name

packages/router/src/router.ts
Fix #1850
I need to test this more as it could have other consequences. For the moment a workaround is to avoid the navigation duplication:
```js
router.beforeEach((to, from) => {
if (!localStorage.getItem("JWT") && to.name !== "Home") {
console.log("intercepting, no token, URL should be: ", from.fullPath);
if (from.name === 'Home') return false // avoid duplicated navigation
return { name: "Home" };
}
});
```
=> fix(router): allow duplicated navigation on back + redirect

packages/router/src/RouterLink.ts
```vue
<template>
<RouterLink to="/some-page" view-transition>
Go to some page
</RouterLink>
</template>
```
Limitations:
- Since it the view transition triggers right away, the DOM visually freezes until the navigation is completed but it still allows to have a nice effect with minimal code
[Example by Evan](https://play.vuejs.org/#eNq9V2tv2zYU/SusO8ByZ0mOUxSY5rjZimLdgG1FW2wD5n2gJdpmIpEaSSXOMv/3HZJ6+RHv8WFtg0r3ce65D14qj4OCchHd6EEy4EUplSGPJFWMGvZVWZIdWSlZkOFdxYYLURtYhRdHMS3LyCtbdeP/PSukenjHtcF/41r4QVaGqT5uqJyog38nC/YTZ/dtjEZQB2pYLOG3Z9dKWkapFNoQF0CTK/LrQhDQK6nZJGQYD0FKAkwwYZIu7G68b0Yt7L5tF9sa/3YQSiFUP9vg0QJufCGSU9UJRi6mJ4rH3chBNm0I8AMJIVGlWeBj+PdCVsIEw+dow3A0GA/qdqCZM50qXhqimanKea85gHhf6c3P3Gw+KSo0N1yKtiFRXOsxEr0SriVyOukZgEhj88laMXI1x3PAIkPVmpkoo4aCRWQkTGex5wVGeDGsKHPkiDdCZpuL+TuW59IO2LNZj …
=> feat(link): add view-transition prop

packages/docs/guide/essentials/history-mode.md
Hello, and thank you for such a helpful library! 😄 
I'm submitting a suggestion to reorder the **Different History modes** section so that HTML5 comes first, since it's the recommended way.
=> docs: reorder history modes

.github/contributing.md, package.json, pnpm-lock.yaml, scripts/verifyCommit.mjs
While reviewing #2464, I noticed that the formatting was incorrect on the imports. I wondered why that hadn't been automatically fixed on commit.
There are several reasons why this isn't working. I didn't want to create a huge PR, so here I've just switched `yorkie` to `simple-git-hooks`. By itself, this wouldn't have prevented the formatting problems seen in #2464, as it isn't checking `.mjs` files. Changing that is more complicated than it sounds, so I'll open other PRs to fix the other problems.
`yorkie` doesn't work with pnpm, the git hooks aren't created. For anyone who cloned the repo before it used pnpm, it might appear as though everything is working fine, but the git hooks aren't created for a fresh clone.
Most of the Vue ecosystem has moved away from `yorkie` and is now using …
=> chore: change yorkie to simple-git-hooks

package.json, packages/playground/index.html, packages/router/__tests__/RouterLink.spec.ts, packages/router/__tests__/guards/guardsContext.spec.ts, packages/router/__tests__/lazyLoading.spec.ts, packages/router/e2e/encoding/index.html, packages/router/e2e/guards-instances/index.html, packages/router/e2e/hash/index.html, packages/router/e2e/index.html, packages/router/e2e/keep-alive/index.html, packages/router/e2e/modal/index.html, packages/router/e2e/multi-app/index.html, packages/router/e2e/scroll-behavior/index.html, packages/router/e2e/suspense/index.html, packages/router/e2e/transitions/index.html, packages/router/src/RouterLink.ts, packages/router/src/RouterView.ts, packages/router/src/location.ts, packages/router/src/navigationGuards.ts, packages/router/src/query.ts, packages/router/src/typed-routes/params.ts, packages/router/src/typed-routes/route-location.ts, packages/router/src/typed-routes/route-map.ts, pnpm-lock.yaml
Apart from `package.json` and `pnpm-lock.yaml`, all the changes come from running `lint:fix`.
Prettier 2 doesn't support using `with { type: 'json' }` for imports, which we're using in some `.mjs` files. Currently we aren't linting `.mjs` files, but that's something I'd eventually like to change. Upgrading Prettier is a first step towards that.
=> chore: upgrade to Prettier 3

packages/docs/guide/essentials/redirect-and-alias.md, packages/docs/zh/guide/essentials/redirect-and-alias.md
The current example in the `Relative redirecting` section of the docs seems misleading:
```js
const routes = [
{
// will always redirect /users/123/posts to /users/123/profile
path: '/users/:id/posts',
redirect: to => {
// the function receives the target route as the argument
// a relative location doesn't start with `/`
// or { path: 'profile'}
return 'profile'
},
},
]
```
Returning the value `'profile'` won't necessarily yield a path of `/users/123/profile`. A relative path is resolved relative the current active route, not the `to` route.
When this was first pointed out to me I thought it was a bug, but based on #1902 it seems it's considered correct. The reproduction provided in #1902 is almost identical to the example in the docs - I'm not sure whether **posva** was aware of that …
=> docs: fix relative redirect example

packages/docs/.vitepress/theme/components/MadVueBanner.vue
I've left compatibility with VS banner commented just in case it as to be reused
=> docs: activate madvue banner

packages/docs/run-typedoc.mjs, packages/docs/typedoc-markdown.mjs, packages/router/size-checks/rollup.config.mjs, scripts/check-size.mjs
The expression path.dirname(new URL(import.meta.url).pathname) returns a path with a double G:\ prefix on nodejs v20, causing path resolution errors. Modify it using a ternary operator to make it compatible with nodejs v20.
=> chore: build path compatibility with nodejs v20

packages/docs/guide/advanced/typed-routes.md, packages/playground/src/main.ts, packages/router/__tests__/routeLocation.test-d.ts, packages/router/src/index.ts, packages/router/src/typed-routes/route-map.ts, packages/router/src/types/index.ts, packages/router/src/useApi.ts, packages/router/test-dts/typed-routes.test-d.ts
In an app (with a typed router) where route `/a/b` is a child of route `/a`, this makes `useRoute('/a')` return `RouteLocationNormalizedLoadedTyped<RouteNamedMap, "/a"> | RouteLocationNormalizedLoadedTyped<RouteNamedMap, "/a/b">`.
It works in a recursive manner, so whenever route `/a/b/c` is added as a child of `/a/b`,  `useRoute('/a')` will return `RouteLocationNormalizedLoadedTyped<RouteNamedMap, "/a"> | RouteLocationNormalizedLoadedTyped<RouteNamedMap, "/a/b">` | RouteLocationNormalizedLoadedTyped<RouteNamedMap, "/a/b/c">`.
Of course `useRoute('/a/b/c')` will *only* return `RouteLocationNormalizedLoadedTyped<RouteNamedMap, "/a/b/c">`.
> [!NOTE] 
> This PR is intended to be paired with the following `unplugin-vue-router` PR: https://github.com/posva/unplugin-vue-router/pull/602
> That …
=> feat: make typed `useRoute(currentRouteName)` return children route types as well

.prettierignore, package.json, packages/docs/.vitepress/config/index.ts, packages/docs/.vitepress/config/shared.ts, packages/docs/.vitepress/theme/index.ts
There are several files that aren't currently being formatted by Prettier. I've tried to expand that to include more files.
- Add `mjs` and `mts` extensions.
- Add `*.html` to `lint-staged`.
- Expand the paths in `lint:script` to cover more files in `packages`, as well as `scripts`.
Changing the paths in `lint:script` is probably the trickiest part. It's not entirely clear to me whether I've got those paths correct.
It's worth noting that `lint-staged` doesn't take those paths into account, it just formats anything with the appropriate extensions. However, it only formats *staged* files, so anything in `.gitignore` is implicitly ignored by `lint-staged`.
Prettier 3 does take the root `.gitignore` into account, but it doesn't consider nested `.gitignore` files, which are being used in this …
=> chore: lint more files

packages/docs/guide/advanced/transitions.md
As discussed in #2392, the examples in the documentation don't respect the `appear` property on transitions. I added a new section explaining that, and pointing to more complex scenarios documented in the Vue docs.
=> docs: document appear transition behaviour (#2392)

packages/router/__tests__/history/memory.spec.ts, packages/router/src/history/memory.ts
Memory history now stores the `state` property through navigations.
=> feat: memory history stores state

packages/docs/guide/advanced/scroll-behavior.md, packages/docs/zh/guide/advanced/scroll-behavior.md
Closes https://github.com/vuejs/router/issues/2443
Open to any and all suggestions/comments.
I've added a translation for `zh` using some GenAI, so let me know if that is okay.
=> docs: add advanced offsets content for scrollBehavoir

packages/router/src/errors.ts
`Property 'canceled' does not exist on type 'typeof NavigationFailureType'. Did you mean 'cancelled'?`
Copied from the example of { isNavigationFailure } Function: [isNavigationFailure](https://router.vuejs.org/api/functions/isNavigationFailure.html)
```ts
router.afterEach((to, from, failure) => {
// Any kind of navigation failure
if (isNavigationFailure(failure)) {
// ...
}
// Only duplicated navigations
if (isNavigationFailure(failure, NavigationFailureType.duplicated)) {
// ...
}
// Aborted or canceled navigations
if (
isNavigationFailure(failure, NavigationFailureType.aborted | NavigationFailureType.canceled) // TypeError
) {
// ...
}
})
```
=> docs: fix isNavigationFailure function example

packages/router/src/history/html5.ts
fix #2536
On iOS safari, scroll to the middle of the page, refresh, it'll go back to top instead of going back to the correct position.
It behaves properly in chrome for e.g., it'd restore the scroll position.
It's going back to the top of the page instead of restoring the scroll position.
---
The code window.addEventListener('beforeunload', beforeUnloadListener) does not trigger on iOS, we should use window.addEventListener('pagehide', ...) instead
=> fix(router): use pagehide for iOS navigation
