- src/index.ts
- test-dts/createRouter.test-d.ts
You currently have to type the `next` arg manaully in a navigation guard
> feat(types): export NavigationGuardNext

- __tests__/warnings.spec.ts
- src/router.ts
Warns when the route is not found
> test: add test for route not matched

- README.md
> nitpicking README

- src/RouterLink.ts
- src/RouterView.ts
- src/errors.ts
- src/history/html5.ts
- src/matcher/index.ts
- src/matcher/pathMatcher.ts
- src/matcher/pathParserRanker.ts
- src/router.ts
- src/utils/index.ts
> fix: use assign to align with Vue browser support

- playground/shim.d.ts
first-pr : update `shims-vue.d.ts`
> chore: ComponentOptions -> Component

- playground/views/ComponentWithData.vue
- playground/views/Home.vue
- playground/views/Nested.vue
- playground/views/NestedWithId.vue
- playground/views/NotFound.vue
- playground/views/User.vue
- Remove unused imports for **inject**
- Remove unused imports for **guardSymbol**(no definition found in `../../src/components/View'`)
> refactor: remove unused imports and code

- src/router.ts
- src/scrollBehavior.ts
optimized with one single for loop
> refactor(src): optimized with one single for loop

- docs/guide/advanced/composition-api.md
> docs: typo (#478) [skip ci]

- docs/guide/advanced/extending-router-link.md
This PR makes the example much more explicit.
> docs: fix extending router-link example

- docs/guide/essentials/history-mode.md
[Read original post here](https://github.com/vuejs/vuepress/issues/457#issuecomment-463745656)
> docs: add netlify section for history mode rewrites (#510) [skip ci]

- README.md
> docs: typo (#518) [skip ci]

- docs/.vitepress/config.js
- docs/.vitepress/theme/Layout.vue
- docs/.vitepress/theme/components/AlgoliaSearchBox.vue
- docs/guide/essentials/navigation.md
- package.json
- yarn.lock
Depends on https://github.com/vuejs/vitepress/pull/99
> docs: add algolia search

- docs/guide/advanced/navigation-failures.md
line#52~54, There are extra brackets
> doc: remove extra brackets

- __tests__/warnings.spec.ts
- e2e/hash/index.ts
- e2e/specs/hash.js
- src/router.ts
> fix: trigger redirect on popstate

- docs/.vitepress/config.js
> docs: Add favicon to docs in vitepress config

- src/router.ts
> feat(scroll): allow modifying scrollBehavior in options

- docs/guide/index.md
> docs: typo (#644) [skip ci]

- docs/.vitepress/theme/Layout.vue
- docs/.vitepress/theme/components/CarbonAds.vue
- package.json
- yarn.lock
This reverts commit 5584927a8cf6c5cf68020fc1ce1d907fdb49cc38.
> docs: rollback vitepress

- docs/api/index.md
> docs: fix link in useRouter api doc

- docs/guide/advanced/composition-api.md
Added information about how to import the composition API functions (useRouter & useRoute).
> docs: add imports

- __tests__/RouterLink.spec.ts
- __tests__/RouterView.spec.ts
- __tests__/guards/beforeRouteEnterCallback.spec.ts
- __tests__/mount.ts
- package.json
- yarn.lock
> refactor(test): replace custom testing utils with VTU

- __tests__/lazyLoading.spec.ts
- __tests__/warnings.spec.ts
- src/navigationGuards.ts
> feat(warn): warn defineAsyncComponent usage in routes

- docs/guide/advanced/extending-router-link.md
> docs: typo

- src/devtools.ts
Fixing the id (currently is `0`) and the label (more useful for user).
> fix(devtools): id and label

- docs/guide/advanced/navigation-guards.md
> docs: improve guards

- e2e/guards-instances/index.ts
- e2e/specs/suspense.js
- e2e/suspense/index.html
- e2e/suspense/index.ts
- src/RouterView.ts
> fix(view): correctly reuse instance guards

- __tests__/guards/beforeRouteUpdate.spec.ts
- src/router.ts
> fix(guards): ensure beforeRouteUpdate works with aliases

- src/router.ts
> fix($route): Make $route have an enumerable type

- docs/api/index.md
- docs/zh/api/index.md
> docs: add a note for use functional component

- docs/guide/essentials/route-matching-syntax.md
Feel free to close this PR if this is not an extra comma by mistake.
> docs: trim extra comma

- docs/.vitepress/config.js
Add `editLinkText` and `lastUpdated` in vitepress config
> docs: add edit link text and lastUpdated

- docs/api/index.md
I think beforeEach example should be inside beforeEach section
> docs: use beforeResolve

- docs/guide/essentials/history-mode.md
- docs/zh/guide/essentials/history-mode.md
Update the url link in documents written in Chinese.
> docs: update the url of SSR

- docs/guide/advanced/composition-api.md
Added watch to import from vue
> docs: missing import

- src/router.ts
use const statement insteads of let
> chore: use const statement instead of let

- docs/zh/guide/advanced/scroll-behavior.md
missing ',' between object property on line 85
85行对象里的属性之间少了逗号
> missing ',' between object property on line 85

- package.json
https://docs.npmjs.com/cli/v6/configuring-npm/package-json
> chore: specify repository/bugs/homepage [skip ci]

- docs/zh/guide/migration/index.md
> docs: fix dynamic-routing link

- docs/guide/advanced/dynamic-routing.md
- docs/guide/advanced/navigation-failures.md
- docs/guide/advanced/navigation-guards.md
- docs/guide/essentials/named-views.md
- docs/guide/essentials/navigation.md
- docs/guide/essentials/redirect-and-alias.md
- docs/guide/essentials/route-matching-syntax.md
- docs/guide/index.md
- docs/introduction.md
add Vue School links for supplemental video material.
> docs: add 8 more Vue School links

- __tests__/matcher/addingRemoving.spec.ts
- src/matcher/index.ts
> feat: warn against named parent routes

- packages/docs/.vitepress/config.ts
Update the link to `CHANGELOG.md` in zh docs.
> docs: update changelog link

- README.md
Add a line to make the document look more harmonious
> docs: add a blank line

- .github/contributing.md
replace yarn with pnpm in contributing.md
> docs: replace yarn with pnpm in contributing.md

- packages/docs/.vitepress/config.ts
the document's "Suggest changes to this page" link is wrong. 
when clicking the link
> The 'vuejs/router' repository doesn't contain the 'docs/xxx.md' path in 'main'.
> fix: edit link not exist

- packages/router/src/RouterLink.ts
- packages/router/src/RouterView.ts
- packages/router/src/encoding.ts
- packages/router/src/errors.ts
- packages/router/src/globalExtensions.ts
- packages/router/src/history/common.ts
- packages/router/src/history/hash.ts
- packages/router/src/history/html5.ts
- packages/router/src/history/memory.ts
- packages/router/src/location.ts
- packages/router/src/matcher/index.ts
- packages/router/src/matcher/pathParserRanker.ts
- packages/router/src/matcher/types.ts
- packages/router/src/navigationGuards.ts
- packages/router/src/router.ts
- packages/router/src/types/index.ts
Just some grammar fixes my IDE highlighted
> docs: spelling fixes in doc blocks

- packages/docs/zh/api/index.md
> docs: improve Chinese translation

- packages/docs/zh/introduction.md
> docs(introduction): update links on zh page from en

- packages/docs/guide/advanced/data-fetching.md
Hi Vue team 😄  I was reading the documentation at https://router.vuejs.org/guide/advanced/data-fetching.html#fetching-before-navigation, and I found the code example quite confusing. I'm coming from version 2 of Vue, and `vm.setData()` method confused me. I've asked myself if that is a new syntax to modify the data component, but it's not. Maybe I'm not the only person that thinks like this. So, I added more context with the method setData in the example 😃. Thanks
> docs: code example on 'Fetching Before Navigation' with a better context

- README.md
the image link got invalid here is the updated one check it out. and thanks
> chore: update ci badge [skip ci]

- packages/docs/guide/advanced/navigation-guards.md
> docs: Update navigation-guards.md

- packages/docs/guide/advanced/meta.md
"who" is used for people
"that" is used for things/objects
> docs: improve sentence

- packages/router/__tests__/scrollBehavior.spec.ts
Maybe the test cases are not correct.
> test: modify test case

- packages/docs/zh/index.md
Home pages tagline chinese translate.
> docs(zh): index tagline translate

- packages/docs/guide/index.md
- packages/docs/zh/guide/index.md
Fix #1236 
First time to work on Open Source project issue
If PR have any problem, please let me know
Thanks!
> docs: Update index.md (fix #1236)

- packages/docs/.vitepress/config/shared.ts
This PR updates uncomments and updates the script of the Vue School top banner.
Feel free to check the deploy preview to see the banner in action.
For more information, please visit: https://vueschool.io/affiliates/banner
> Add Vue School top banner

- packages/docs/zh/guide/advanced/composition-api.md
- packages/docs/zh/guide/advanced/extending-router-link.md
- packages/docs/zh/guide/advanced/lazy-loading.md
- packages/docs/zh/index.md
> docs(zh): sync update to e008551

- packages/docs/zh/api/index.md
> dcos: typo

- packages/docs/guide/advanced/typed-routes.md
- packages/docs/zh/guide/advanced/typed-routes.md
translate [Typed Routes](https://router.vuejs.org/guide/advanced/typed-routes.html)
> docs(zh): typed routes translate

- packages/docs/zh/api/enums/NavigationFailureType.md
- packages/docs/zh/api/interfaces/HistoryState.md
- packages/docs/zh/api/interfaces/NavigationFailure.md
- packages/docs/zh/api/interfaces/RouterOptions.md
@Justineo I translated some API pages. We need to align whether it's a good pattern to go before dealing with the rest part. Thanks.
> docs(zh): translate some API pages

- packages/router/__tests__/RouterView.spec.ts
- packages/router/src/RouterView.ts
fix: https://github.com/vuejs/router/issues/1306
> fix(warn): avoid redundant usage warn

- packages/docs/zh/guide/advanced/composition-api.md
Fix https://github.com/vuejs/router/pull/1773#discussion_r1160765708
> docs(zh): update the translation of active and exact active

- packages/docs/zh/api/enums/NavigationFailureType.md
- packages/docs/zh/api/interfaces/HistoryState.md
- packages/docs/zh/api/interfaces/NavigationFailure.md
- packages/docs/zh/api/interfaces/NavigationGuard.md
- packages/docs/zh/api/interfaces/NavigationGuardNext.md
- packages/docs/zh/api/interfaces/NavigationGuardWithThis.md
- packages/docs/zh/api/interfaces/NavigationHookAfter.md
- packages/docs/zh/api/interfaces/RouteLocation.md
- packages/docs/zh/api/interfaces/RouteLocationMatched.md
- packages/docs/zh/api/interfaces/RouteLocationNormalized.md
- packages/docs/zh/api/interfaces/RouteLocationNormalizedLoaded.md
- packages/docs/zh/api/interfaces/RouteLocationOptions.md
- packages/docs/zh/api/interfaces/RouteMeta.md
- packages/docs/zh/api/interfaces/RouteRecordNormalized.md
- packages/docs/zh/api/interfaces/Router.md
- packages/docs/zh/api/interfaces/RouterHistory.md
- packages/docs/zh/api/interfaces/RouterLinkProps.md
- packages/docs/zh/api/interfaces/RouterOptions.md
- packages/docs/zh/api/interfaces/RouterScrollBehavior.md
- packages/docs/zh/api/interfaces/RouterViewProps.md
Translated the rest of the API references, except several paragraphs with TODO comments.
> docs(zh): translate api interfaces

- packages/docs/.vitepress/config/zh.ts
> docs: fix incorrect link url

- packages/router/src/history/html5.ts
> chore: remove an unnecessary note 'console.log({ deltaFromCurrent })'

- packages/docs/.vitepress/config/index.ts
In this pull request, I am adding the link to the Portuguese version of this documentation.
@Jinjiang @pikax @danielroe @patak-dev
> chore: add link to the portuguese documentation

- packages/docs/guide/advanced/lazy-loading.md
just a suggestion to import inline so management of routes becomes easier.
> docs: lazy loading example

- packages/docs/.vitepress/theme/components/AsideSponsors.vue
This PR is meant to update links for Mastering Pinia and Vue Certification Banners.
> update links for mastering pinia and Vue Certification banners

- packages/docs/zh/guide/advanced/data-fetching.md
> docs(zh): additions `setData` method

- packages/docs/.vitepress/config/shared.ts
- packages/docs/.vitepress/config/zh.ts
ref: https://github.com/vuejs/pinia/pull/2542
> docs(zh): add algolia search box translation

- packages/docs/.vitepress/theme/components/HomeSponsorsGroup.vue
Define props default values using withDefaults.
> chore: defining default values for Props using withDefaults

- packages/docs/guide/index.md
Comment lines are being splitted to avoid horizontal scrolling as in a comment right after.
The comment is in one line and right after there is another comment in multiple lines that avoid horizontal scrolling.
> docs: fix index.md to avoid horizontal scrolling in code

- packages/docs/zh/guide/essentials/navigation.md
> docs(zh): translate the note part of programmatic_navigation to Chinese

- packages/docs/zh/api/interfaces/RouterScrollBehavior.md
> docs(zh): translate the description section of RouterScrollBehavior to Chinese

- packages/docs/zh/guide/migration/index.md
> docs(zh): translate the currentRoute section of migration to Chinese

- packages/docs/zh/api/interfaces/RouteRecordNormalized.md
> docs(zh): translate the rest of RouteRecordNormalized to Chinese

- packages/docs/guide/essentials/nested-routes.md
Use UTF-8 box drawing characters so it looks like this:
```
/user/johnny/profile                   /user/johnny/posts 
┌──────────────────┐                  ┌──────────────────┐
│ User             │                  │ User             │
│ ┌──────────────┐ │                  │ ┌──────────────┐ │
│ │ Profile      │ │  ●────────────▶  │ │ Posts        │ │
│ │              │ │                  │ │              │ │
│ └──────────────┘ │                  │ └──────────────┘ │
└──────────────────┘                  └──────────────────┘
```
> Update nested-routes.md to use UTF-8 box drawing characters

- packages/docs/zh/guide/index.md
docs(zh): fix the order of useRouter() and useRoute() in packages/docs/zh/guide/index.md #2277
> docs(zh): fix the order of useRouter() and useRoute() in packages/docs/zh/guide/index.md

- packages/docs/guide/advanced/dynamic-routing.md
Fix punctuation and comma splices in a few spots.
> docs: fix punctuation

- packages/docs/guide/essentials/route-matching-syntax.md
reorder 2 markdown symbols that I think are more appropriate.
> docs: reorder symbols

- packages/docs/guide/essentials/named-views.md
By changing indention and line wrapping the example is easier to follow.
> docs: improve example line wrapping

- .github/contributing.md
Updated contributing.md references from JEST to VITEST.
> docs: updated contributing.md references from JEST to VITEST

- packages/docs/.vitepress/theme/components/MadVueBanner.vue
Update old ticket name and discount amount
> docs(madvue): update ticket discount

- packages/docs/installation.md
> docs: add bun command examples
